# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

metropolisC <- function(x, beta, num_iterations_mcmc, other_params) {
    .Call('ais_metropolisC', PACKAGE = 'ais', x, beta, num_iterations_mcmc, other_params)
}

metropolisC2 <- function(x, beta, num_iterations_mcmc, other_params) {
    .Call('ais_metropolisC2', PACKAGE = 'ais', x, beta, num_iterations_mcmc, other_params)
}

metropolisCbeta <- function(x, beta, num_iterations_mcmc, other_params) {
    .Call('ais_metropolisCbeta', PACKAGE = 'ais', x, beta, num_iterations_mcmc, other_params)
}

faC <- function(e) {
    .Call('ais_faC', PACKAGE = 'ais', e)
}

JacobianC <- function(e) {
    .Call('ais_JacobianC', PACKAGE = 'ais', e)
}

log_likelihoodC <- function(theta, powers_dirichlet) {
    .Call('ais_log_likelihoodC', PACKAGE = 'ais', theta, powers_dirichlet)
}

e_to_pC <- function(e) {
    .Call('ais_e_to_pC', PACKAGE = 'ais', e)
}

fbC <- function(e, other_params) {
    .Call('ais_fbC', PACKAGE = 'ais', e, other_params)
}

rcpp_hello_world <- function() {
    .Call('ais_rcpp_hello_world', PACKAGE = 'ais')
}

