# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

metropolisC <- function(x, beta, num_iterations_mcmc, other_params) {
    .Call('ais_metropolisC', PACKAGE = 'ais', x, beta, num_iterations_mcmc, other_params)
}

metropolisC2 <- function(x, beta, num_iterations_mcmc, rproposal_fn_xpsexp, dproposal_fn_xpsexp, other_params) {
    .Call('ais_metropolisC2', PACKAGE = 'ais', x, beta, num_iterations_mcmc, rproposal_fn_xpsexp, dproposal_fn_xpsexp, other_params)
}

metropolisCbeta <- function(x, beta, num_iterations_mcmc, rproposal_fn_xpsexp, dproposal_fn_xpsexp, other_params, debug) {
    .Call('ais_metropolisCbeta', PACKAGE = 'ais', x, beta, num_iterations_mcmc, rproposal_fn_xpsexp, dproposal_fn_xpsexp, other_params, debug)
}

faC <- function(e) {
    .Call('ais_faC', PACKAGE = 'ais', e)
}

JacobianC <- function(e) {
    .Call('ais_JacobianC', PACKAGE = 'ais', e)
}

logJacobianC <- function(e) {
    .Call('ais_logJacobianC', PACKAGE = 'ais', e)
}

log_likelihoodC <- function(theta, powers_dirichlet, theta_sum_list) {
    .Call('ais_log_likelihoodC', PACKAGE = 'ais', theta, powers_dirichlet, theta_sum_list)
}

#' @title
#' e_to_pC
#' @descriptinocp
#' Convert e to p representation.
#' 
#' @param e a vector
#' 
#' @details
#' \code{e_to_pC} takes a vector.
#' @export
e_to_pC <- function(e) {
    .Call('ais_e_to_pC', PACKAGE = 'ais', e)
}

#' @title
#' fbC
#' @descriptinocp
#' 
#' 
#' @param e a vector containing values of the parameters.
#' @param other_params a list containing other parameters
#' 
#' @details
#' \code{e_to_pC} takes a vector.
#' @export
fbC <- function(e, other_params) {
    .Call('ais_fbC', PACKAGE = 'ais', e, other_params)
}

rproposal_distr <- function(x, n, mult) {
    .Call('ais_rproposal_distr', PACKAGE = 'ais', x, n, mult)
}

dbeta_cond_distr <- function(x, y, n, mult) {
    .Call('ais_dbeta_cond_distr', PACKAGE = 'ais', x, y, n, mult)
}

putFunPtrInXPtr <- function(distr_name) {
    .Call('ais_putFunPtrInXPtr', PACKAGE = 'ais', distr_name)
}

getCondDensityFuncXPtr <- function(distr_name) {
    .Call('ais_getCondDensityFuncXPtr', PACKAGE = 'ais', distr_name)
}

rcpp_hello_world <- function() {
    .Call('ais_rcpp_hello_world', PACKAGE = 'ais')
}

